name: who_listen_me
version: 0.2.0
description: >
 Who listen me is a small api to know you listen you on social networks. Supports Google+ and Twitter.
author: Nicolas Francois @nicofrancois
homepage: https://github.com/dartlangfr/who_listen_me
dependencies:
  unittest:
    sdk: unittest